import "../styles/style.css";
import "../styles/reset.css";
import "../styles/playlist.css";
import "../styles/weather.css";
import "../styles/quote.css";
import "./playlist.js";
import "./weather.js";
import "./quote.js";
import "./random1.js";
import "./random2.js";
import "../styles/todo.css"
import "../styles/sticker.css"